---
- name: add dev user
  user: name=dev password={{ user_dev_password }} groups=audio,lp,optical,storage,video,wheel,games,power,scanner

- name: ensure base-devel is installed
  pacman: name=base-devel state=installed

- name: ensure netatalk is installed
  pacman: name=netatalk state=installed
- name: copy avahi afp services file
  copy: src=etc/avahi/services/afpd.service dest=/etc/avahi/services/afpd.service
- name: enable netatalk service
  service: name=netatalk enabled=true state=started
- name: enable home directory sharing
  ini_file: dest=/etc/afp.conf state=present section='Homes' option='basedir regex' value='/home'

- name: set INEGRITY_CHECK to sha512
  lineinfile: dest=/etc/makepkg.conf state=present regexp='^INTEGRITY_CHECK' line='INTEGRITY_CHECK=(sha512)'
